version: "2.4"

services:
  test:
    build:
      context: ./
      dockerfile: test.docker
    volumes:
      - .:/go/src/github.com/airspacetechnologies/go-env
    working_dir: /go/src/github.com/airspacetechnologies/go-env
    environment:
      - GO111MODULE=on
    command: sh -c "make test"
